spring:
  application:
    name: distributed-job-processor
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      externalServiceCircuitBreaker:
        sliding-window-type: COUNT_BASED  # COUNT_BASED or TIME_BASED
        sliding-window-size: 10          # Number of calls to consider for the circuit breaker
        failure-rate-threshold: 50       # Percentage of failures to trigger the circuit breaker
        wait-duration-in-open-state: 10s # Time the circuit breaker stays open before attempting recovery
        permitted-number-of-calls-in-half-open-state: 5 # Calls allowed in half-open state
        minimum-number-of-calls: 5       # Minimum calls to evaluate failure rate
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      externalServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - com.overpathz.distributedjobprocessor.client.ClientProviderNetworkException
        ignore-exceptions:
          - java.lang.InterruptedException

logging:
  level:
    root: INFO
